### ISSUE TITLE
Load file from internal storage

### ISSUE THREAD

**Issue by Mayur907** [LottieFiles/dotlottie-android#23]
how to load .lottie file from internal storage 
I tried using a byte array and passing this byte array to the Data() method but not work and 
same as Json() method

**Comment by theashraf** [comment]
Maybe try this: 

```rs
// imports

@Preview
@Composable
fun DotLottiePreview() {
    DotLottieAnimation(
        source = DotLottieSource.Asset("file.json") // or file.lottie
    )
}
```

As mentioned in the documentation:
https://developers.lottiefiles.com/docs/dotlottie-android/usage/basic-usage/#from-an-asset

**Comment by Mayur907** [comment]
Thanks for your answer 
but I try to load the .lottie file from my device's internal storage ("/sdcard/Android/media/com.example.dotlottie//anim/bg1.lottie) so which method I use and how

**Comment by theashraf** [comment]
@Mayur907 Have you tried `DotLottieSource.Asset("path/to/file.lottie")`?

**Comment by Mayur907** [comment]
> @Mayur907 Have you tried `DotLottieSource.Asset("path/to/file.lottie")`?

yes I tried but not working

**Comment by afsalz** [comment]
Hi @Mayur907

If you are loading files using `DotLottieSource.Asset` please make sure the file are stored as assets inside your asset folder. It utilises the function `context.assets.open(assetPath)` to read the files stored as assets.

Here are some sample code on how you could use `Json` and `Data`

In order to use `DotLottieSource.Json` you can just pass the lottieJSON as a string
```
@Composable
fun JsonExample() {
    val lottieJson = """
       {"v":"5.10.0","fr":....}
    """.trimIndent()


    Column {
        DotLottieAnimation(
            source = DotLottieSource.Json(lottieJson),
            autoplay = true,
            loop = true)
    }
}
```

`DotLottieSource.Data` can be used when you have access to .lottie file as byteArray. This is useful if your `.lottie` file is in a remote server and you want to have more control over the file download.
```
suspend fun downloadLottieAnimation(urlString: String): ByteArray = withContext(Dispatchers.IO) {
    try {
        val bytes = java.net.URL(urlString).openStream().readBytes()
        bytes
    } catch (e: Exception) {
        ByteArray(0) // return an empty byte array in case of failure
    }
}
@Composable
fun JsonExample() {
    val scope = rememberCoroutineScope()
    var lottieByteArray by remember { mutableStateOf(ByteArray(0)) }

    LaunchedEffect(Unit) {
        scope.launch {
            lottieByteArray = downloadLottieAnimation("https://lottie.host/294b684d-d6b4-4116-ab35-85ef566d4379/VkGHcqcMUI.lottie")
        }
    }

    Column {
        lottieByteArray.let {
            if (lottieByteArray.isEmpty()) {
                Text(text = "Downloading Lottie Animation")
            } else {
                DotLottieAnimation(
                    source = DotLottieSource.Data(lottieByteArray),
                    autoplay = true,
                    loop = true)
            }
        }
    }
}
```

If you don't mind please share with us your code, so that we can investigate the issue you're facing.

**Comment by Mayur907** [comment]
Thanks @afsalz
